import type { Locale, RdAnnualCopy } from './i18n'

export const rdAnnualPlainCopy: Record<Locale, Partial<RdAnnualCopy>> = {
  'en-US': {
    eyebrow: 'YEAR-BY-YEAR CHECK',
    title: 'Does the pattern look similar in different years?',
    description: 'Each bar compares the monthly stock ranking from an R&D measure with the later return ranking. It shows whether the two rankings moved together, not how much a portfolio earned.',
    extensionTitle: 'A separate reconstruction of older data',
    extensionDescription: 'This look back uses data build {vintage} and stock prices requested through {end}, starting at {start}. It is separate from the corrected main results above.',
    publicNotice: 'The archive does not contain every version of every old financial report. Months and years can overlap, so this chart cannot establish that the pattern will continue in new data.',
    factorLabel: 'R&D measure',
    horizonLabel: 'Return measured over',
    fwd20: 'Next 20 trading days',
    fwd220: 'Next 220 trading days',
    signalWindow: 'Months included',
    chartTitle: 'Average monthly rank correlation by year',
    chartDescription: 'Bars show whether the R&D ranking and later-return ranking tended to agree in each year. Gray dots mean no usable comparison was available.',
    measureNote: 'Rank IC is the correlation between two ranked lists: the R&D ranking and the later stock-return ranking. “Top minus bottom” compares the average later return of the highest and lowest signal groups before costs. Neither number is a portfolio return.',
    tableLabel: 'Year-by-year R&D comparisons',
    year: 'Year',
    months: 'Usable monthly comparisons',
    rankIc: 'Average rank correlation',
    topBottom: 'High-signal vs low-signal return',
    coverage: 'Share of stocks with data',
    medianNames: 'Typical number of stocks',
    status: 'What data was available',
    overlapNote: 'The 220-day return windows overlap when signals are formed monthly. Read these year-by-year numbers as a description of this historical sample, not as independent tests. The future holdout remains sealed.',
    annualUnavailable: 'Year-by-year evidence is temporarily unavailable.',
    factors: {
      rd_mv: 'R&D expense / market value',
      rd_mv_resid: 'R&D / market value after adjustments',
      rd_ev: 'R&D / estimated enterprise value',
      rd_capitalized: 'Five-year reconstructed R&D / market value',
      rd_sales: 'R&D expense / revenue',
      rd_assets: 'R&D expense / assets',
      rd_growth: 'Change in R&D expense',
    },
    statuses: {
      missing_lookback: 'Not enough earlier data',
      below_minimum_cross_section: 'Too few stocks to compare',
      no_eligible_cross_section: 'No eligible stocks that year',
      observed: 'Reconstructed from available records',
      reconstructed_backfill: 'Older data added retrospectively',
      partial_year: 'Partial year',
      no_mature_labels: 'Return window has not finished',
    },
  },
  'zh-CN': {
    eyebrow: '按年份检查结果是否一致',
    title: '换到不同年份，看到的关系还相似吗？',
    description: '每根柱子汇总这一年里每月的比较：先按研发指标给股票排序，再看之后的收益排序是否相似。它显示两种排序是否同向变化，不代表组合赚了多少。',
    extensionTitle: '单独整理的较早历史数据',
    extensionDescription: '这部分回溯使用数据版本 {vintage}，行情从 {start} 起、更新到 {end}。它与上方修正后的主要结果分开统计。',
    publicNotice: '旧财报的每一个历史版本并未全部留存。不同月份和年份的观察可能互相重叠，因此这张图不能证明这种关系会在新数据里继续出现。',
    factorLabel: '研发指标',
    horizonLabel: '收益观察期',
    fwd20: '随后 20 个交易日',
    fwd220: '随后 220 个交易日',
    signalWindow: '纳入的月份',
    chartTitle: '各年平均月度排序相关程度',
    chartDescription: '柱子表示研发指标排序与之后收益排序在该年有多一致。灰点表示该年没有可用比较。',
    measureNote: 'Rank IC（秩相关）比较两份排序名单：按研发指标排出的名次，以及按之后股票收益排出的名次。“高信号组减低信号组”比较信号最高组与最低组之后的平均收益，尚未扣成本。这两个数都不是组合收益。',
    tableLabel: '逐年研发指标比较',
    year: '年份',
    months: '可用的月度比较次数',
    rankIc: '平均排序相关程度',
    topBottom: '高信号组与低信号组的收益差',
    coverage: '有数据的股票占比',
    medianNames: '每期典型股票数',
    status: '当年数据情况',
    overlapNote: '每月形成信号、观察之后 220 个交易日时，相邻观察期会重叠。逐年数字只描述这段历史资料，不能当作互相独立的多次验证。未来留出期仍封存。',
    annualUnavailable: '逐年数据暂时无法加载。',
    factors: {
      rd_mv: '研发费用 / 市值',
      rd_mv_resid: '调整其他因素后的研发 / 市值',
      rd_ev: '研发费用 / 企业价值估算',
      rd_capitalized: '近五年还原研发费用 / 市值',
      rd_sales: '研发费用 / 收入',
      rd_assets: '研发费用 / 资产',
      rd_growth: '研发费用变化',
    },
    statuses: {
      missing_lookback: '缺少足够的历史数据',
      below_minimum_cross_section: '可比较的股票太少',
      no_eligible_cross_section: '该年没有符合条件的股票',
      observed: '根据现有记录还原',
      reconstructed_backfill: '事后补齐的较早数据',
      partial_year: '只有部分月份',
      no_mature_labels: '收益观察期尚未结束',
    },
  },
}
