import BarChart from '../components/BarChart'
import MetricCard from '../components/MetricCard'
import ContextStrip from '../components/ContextStrip'
import type { Alpha810FactorEvidence, Alpha810Snapshot } from '../types'
import { useLocale } from '../i18n'

function metric(value: number | null, english = false, digits = 4) {
  return value === null || !Number.isFinite(value) ? english ? 'No data' : '暂无数据' : value.toFixed(digits)
}

export default function Alpha810FactorPage({ factor, snapshot }: { factor?: Alpha810FactorEvidence; snapshot: Alpha810Snapshot }) {
  const { locale, copy } = useLocale()
  const english = locale === 'en-US'
  const sensitivity = factor ? snapshot.inference_sensitivity?.factors[factor.name] : undefined
  const qValue = (value: number | null | undefined) => value == null || !Number.isFinite(value) ? '—' : value < 0.0001 ? value.toExponential(2) : value.toFixed(4)
  if (!factor) return <main className="empty"><h1>{english ? 'Alpha factor not found' : '未找到 Alpha 因子'}</h1><p>{english ? 'This factor is not in the current public snapshot.' : '这个因子不在当前公开快照中。'}</p><a href={`${import.meta.env.BASE_URL}alpha810`}>{english ? 'Back to Alpha 810' : '返回 Alpha 810'}</a></main>
  const groupLabels = factor.group_returns.map((item) => `G${item.group}`)
  const groupValues = factor.group_returns.map((item) => item.mean_return)
  const firstGroupReturn = factor.group_returns[0]?.mean_return
  const lastGroupReturn = factor.group_returns[factor.group_returns.length - 1]?.mean_return
  const topBottomSpread = firstGroupReturn !== null && firstGroupReturn !== undefined && lastGroupReturn !== null && lastGroupReturn !== undefined ? lastGroupReturn - firstGroupReturn : null
  return <main className="page factor-detail-page">
    <a className="back" href={`${import.meta.env.BASE_URL}alpha810`}>← {english ? 'Alpha 810 factor catalog' : 'Alpha 810 因子目录'}</a>
    <section className="detail-head"><p className="eyebrow">{factor.family} / PUBLIC EVIDENCE</p><h1>{factor.name}</h1><p className="lede">{english ? 'Aggregate cross-sectional diagnostics from the current public snapshot.' : '当前公开快照中的横截面聚合诊断。'}</p></section>
    <ContextStrip items={[{ label: english ? 'Data version' : '数据版本', value: snapshot.data_version }, { label: english ? 'Observation range' : '观测区间', value: `${snapshot.dataset.date_start ?? '—'} → ${snapshot.dataset.date_end ?? '—'}` }, { label: english ? 'Coverage' : '覆盖率', value: factor.coverage.ratio === null ? '—' : `${(factor.coverage.ratio * 100).toFixed(1)}%` }, { label: english ? 'Return field' : '收益字段', value: snapshot.dataset.return_column }]} />
    <section className="panel plain-reading"><p className="eyebrow">{english ? 'START HERE' : '先看这里'}</p><h2>{english ? 'What these numbers mean' : '这些数字分别说明什么'}</h2><p>{english ? 'IC checks whether higher factor scores tend to line up with higher later returns. RankIC asks the same question using stock order instead of score size. A positive-rate percentage tells you on how many dates the relationship pointed upward. None of these is a portfolio return.' : 'IC 看因子分数较高的股票，之后是否也倾向于有较高收益；RankIC 不比较分数差多少，而比较股票排序是否与之后的收益排序一致。正值比例表示这种关系在多少个有效日期上是正的。这些统计都不是组合收益。'}</p><p>{english ? 'IR compares the average IC or RankIC with how much it varied from date to date. The group spread subtracts the average return of the lowest-score group from that of the highest-score group. Both are descriptive summaries before compounding and trading costs.' : 'IR 把 IC 或 RankIC 的平均值与它在不同日期之间的波动相比。分组收益差是最高分组的平均收益减去最低分组的平均收益。这些都是描述性汇总，未复利，也未扣交易成本。'}</p></section>
    <div className="metrics"><MetricCard label={english ? 'Mean IC' : 'IC 均值'} value={metric(factor.ic.mean, english)} note={`IR ${metric(factor.ic.ir, english, 3)}`} /><MetricCard label={english ? 'Mean RankIC' : 'RankIC 均值'} value={metric(factor.rank_ic.mean, english)} note={`IR ${metric(factor.rank_ic.ir, english, 3)}`} /><MetricCard label={english ? 'Positive IC rate' : 'IC 正值比例'} value={factor.ic.positive_rate === null ? english ? 'No data' : '暂无数据' : `${(factor.ic.positive_rate * 100).toFixed(1)}%`} /><MetricCard label={english ? 'Positive RankIC rate' : 'RankIC 正值比例'} value={factor.rank_ic.positive_rate === null ? english ? 'No data' : '暂无数据' : `${(factor.rank_ic.positive_rate * 100).toFixed(1)}%`} /></div>
    <section className="evidence-card-row"><article><span>{copy.alpha810.directionConsistency}</span><strong>{factor.rank_ic.positive_rate === null ? '—' : `${(factor.rank_ic.positive_rate * 100).toFixed(1)}%`}</strong><small>{copy.alpha810.stabilityNote}</small></article><article><span>{copy.alpha810.groupSpread}</span><strong>{metric(topBottomSpread, english, 4)}</strong><small>{copy.alpha810.spreadNote}</small></article><article><span>{copy.alpha810.snapshotInterval}</span><strong>{snapshot.dataset.date_start ?? '—'} → {snapshot.dataset.date_end ?? '—'}</strong><small>{copy.alpha810.fullWindow}</small></article></section>
    <div className="detail-grid"><section className="panel"><p className="eyebrow">COVERAGE</p><h2>{english ? 'Data coverage' : '数据覆盖'}</h2><dl className="research-dl"><div><dt>{english ? 'Valid observations' : '有效观测'}</dt><dd>{factor.coverage.valid_observations.toLocaleString()}</dd></div><div><dt>{english ? 'Total observations' : '总观测'}</dt><dd>{factor.coverage.total_observations.toLocaleString()}</dd></div><div><dt>{english ? 'Return field' : '收益字段'}</dt><dd>{snapshot.dataset.return_column}</dd></div></dl></section><section className="panel"><p className="eyebrow">GROUP RETURNS</p><h2>{english ? 'Average return by factor group' : '因子分组平均收益'}</h2>{factor.group_returns.length ? <BarChart labels={groupLabels} values={groupValues} colors={groupLabels.map((_, index) => index === groupLabels.length - 1 ? '#b64d33' : '#d8a58b')} percent /> : <div className="chart-empty">{english ? 'No grouped returns in this snapshot.' : '当前快照没有分组收益。'}</div>}<p className="panel-note">{english ? 'G1 contains the lowest factor values; G5 the highest. Each bar averages daily cross-sectional mean returns across available dates. Percent per return observation; no compounding or trading costs.' : 'G1 为最低因子值组，G5 为最高组。每根柱先按日计算组内横截面平均收益，再跨可用日期平均；单位为每次收益观测的百分比，未复利、未扣交易成本。'}</p></section></div>
    {factor.annual_slices?.length || factor.regime_slices?.length ? <section className="panel methodology-panel"><p className="eyebrow">{copy.alpha810.annualEvidence}</p><h2>{copy.alpha810.annualTitle}</h2><p className="panel-note">{copy.alpha810.annualNote}</p><div className="table-scroll"><table className="factor-table annual-table"><thead><tr><th>{copy.alpha810.slice}</th><th>{copy.alpha810.validDates}</th><th>{copy.alpha810.meanRankIc}</th><th>{copy.alpha810.positiveRate}</th><th>{copy.alpha810.topBottomSpread}</th></tr></thead><tbody>{[...(factor.annual_slices ?? []).map((slice) => ({ ...slice, kind: copy.alpha810.year })), ...(factor.regime_slices ?? []).map((slice) => ({ ...slice, kind: copy.alpha810.marketRegime }))].map((slice) => { const low = slice.group_returns[0]?.mean_return; const high = slice.group_returns[slice.group_returns.length - 1]?.mean_return; const spread = low == null || high == null ? null : high - low; return <tr key={`${slice.kind}-${slice.label}`}><td>{slice.kind}: {slice.label}</td><td>{slice.valid_dates.toLocaleString()}</td><td>{metric(slice.rank_ic_mean, english)}</td><td>{slice.rank_ic_positive_rate == null ? '—' : `${(slice.rank_ic_positive_rate * 100).toFixed(1)}%`}</td><td>{metric(spread, english)}</td></tr> })}</tbody></table></div>{snapshot.temporal_validation?.market_regime?.status === 'not_provided' ? <p className="panel-note">{copy.alpha810.regimeUnavailable}</p> : null}</section> : null}
    {factor.uncertainty ? <section className="evidence-card-row"><article><span>{copy.alpha810.hacEstimate}</span><strong>{metric(factor.uncertainty.estimate ?? null, english)}</strong><small>{factor.uncertainty.status === 'complete' ? `${factor.uncertainty.method}; ${copy.alpha810.holdingDays}: ${factor.uncertainty.holding_period_days ?? '—'}` : copy.alpha810.inferenceUnavailable}</small></article><article><span>{copy.alpha810.confidenceInterval}</span><strong>{factor.uncertainty.confidence_interval ? `${metric(factor.uncertainty.confidence_interval[0], english)} … ${metric(factor.uncertainty.confidence_interval[1], english)}` : '—'}</strong><small>{factor.uncertainty.status === 'complete' ? copy.alpha810.hacCaveat : copy.alpha810.inferenceUnavailable}</small></article><article><span>{copy.alpha810.rawPValue}</span><strong>{metric(factor.uncertainty.p_value ?? null, english, 4)}</strong><small>{copy.alpha810.rawPValueNote}</small></article><article><span>{copy.alpha810.byQValue}</span><strong>{metric(factor.uncertainty.multiple_testing?.q_value_by ?? null, english, 4)}</strong><small>{copy.alpha810.fdrNote}</small></article></section> : null}
    {sensitivity ? <section className="panel methodology-panel inference-sensitivity"><p className="eyebrow">{english ? 'INFERENCE ROBUSTNESS' : '推断稳健性'}</p><h2>{copy.alpha810.factorLagTitle}</h2><p className="panel-note">{copy.alpha810.factorLagNote}</p><div className="table-scroll"><table className="factor-table sensitivity-table"><thead><tr><th>{copy.alpha810.lag}</th><th>{copy.alpha810.byQ}</th><th>{english ? 'HAC standard error' : 'HAC 标准误'}</th></tr></thead><tbody>{snapshot.inference_sensitivity?.lags.map((lag, index) => { const standardError = sensitivity.by_lag_standard_error[index]; return <tr key={lag}><td>{lag}</td><td>{qValue(sensitivity.by_lag_q[index])}</td><td>{standardError == null ? '—' : standardError.toExponential(3)}</td></tr> })}</tbody></table></div><div className="evidence-metrics"><div><span>{copy.alpha810.bootstrapInterval}</span><strong>{sensitivity.moving_block_bootstrap.confidence_interval ? `${sensitivity.moving_block_bootstrap.confidence_interval[0].toFixed(4)} … ${sensitivity.moving_block_bootstrap.confidence_interval[1].toFixed(4)}` : '—'}</strong></div><div><span>{copy.alpha810.bootstrapSign}</span><strong>{sensitivity.moving_block_bootstrap.sign_probability == null ? '—' : `${(sensitivity.moving_block_bootstrap.sign_probability * 100).toFixed(1)}%`}</strong></div></div><p className="panel-note">{copy.alpha810.inferenceLimits}</p></section> : null}
    <section className="panel methodology-panel"><p className="eyebrow">HOW TO READ THE METRICS</p><h2>{english ? 'Method and limits' : '指标口径与边界'}</h2><p>{english ? 'IC (information coefficient) is the daily Pearson correlation between factor scores and later returns; RankIC is the Spearman correlation between their ranks. IR is the mean daily correlation divided by its population standard deviation across dates. Positive rate is the share of valid dates when the correlation is above zero.' : 'IC（信息系数）是每天因子分数与之后收益的 Pearson 相关系数；RankIC 是两者名次的 Spearman 相关系数。IR 是每日相关系数均值除以其跨日期总体标准差。正值比例表示相关系数大于零的有效日期占比。'}</p><p>{english ? 'G1–G5 are five groups formed by sorting valid stocks from the lowest factor value (G1) to the highest (G5). Each value is the average of daily group mean returns across dates; returns are one-period simple returns, not compounded and not net of costs. The displayed spread is G5 minus G1.' : 'G1–G5 是把有效股票按因子值从低到高分成的五组，G1 最低、G5 最高。组收益是先计算每个日期的组内平均收益，再对日期取平均；它是单期简单收益，未复利、未扣成本。页面展示的组间差是 G5 减 G1。'}</p><p>{english ? 'The BY q-value adjusts for examining 810 factors at once; q-values are adjusted p-values used to limit false discoveries across that family. A lower value is stronger evidence under this check, but it does not remove selection bias or show that a factor will work in a real portfolio. A confidence interval is a range of estimates under the stated method, not a guarantee.' : 'BY q 值是在同时检查 810 个因子后进行的多重检验校正值，用来控制整组检验中的假发现。数值越低，在这项校正检验下证据越强；它不能消除选样偏差，也不能证明因子用于真实组合后有效。置信区间是按所列方法估计的范围，不是保证。'}</p><p>{english ? 'Newey–West (HAC) uncertainty allows daily statistics to vary over time and account for serial dependence; Bartlett weights reduce the influence of more distant lags. Lag settings are sensitivity checks. The 20-session moving-block bootstrap resamples chunks of 20 trading observations, so it preserves some short-run clustering; it remains descriptive and does not correct data snooping.' : 'Newey–West（HAC）不确定性估计允许每日统计量随时间变化，并考虑相邻日期之间的相关性；Bartlett 权重会降低较远滞后期的影响。不同滞后长度用于敏感性检查。20 个交易日移动区块自助法按连续 20 日抽取数据块，以保留部分短期连续性；它仍是描述性诊断，不能校正数据筛选偏差。'}</p><p>{english ? 'The snapshot identifies its target only as next_period_return. Its exact holding interval and execution timing are not specified in this public contract; inspect the upstream data definition before drawing trading conclusions.' : '公开契约仅将目标字段标为 next_period_return，未说明精确持有时长与执行时点；作交易解释前需核对上游数据定义。'}</p><p>{english ? 'Group period counts can differ by factor and group; these values are descriptive aggregate evidence, not a strategy backtest.' : '分组有效期数可能因因子和组别而异；这里是描述性聚合证据，不是策略回测。'}</p></section>
    <section className="research-boundary"><p><strong>{english ? 'Evidence boundary: ' : '研究边界：'}</strong>{snapshot.public_limits.join(' ')}</p></section>
  </main>
}
