import { useMemo, useState } from 'react'
import LineChart from '../components/LineChart'
import MetricCard from '../components/MetricCard'
import { localizeFactorRecord, localizedStatus } from '../researchLocale'
import type { FactorRecord, FundamentalSnapshot, ResearchContext } from '../types'
import { useLocale } from '../i18n'

function value(value: number | null | undefined) {
  return value === null || value === undefined || !Number.isFinite(value) ? 'Unavailable' : value.toFixed(3)
}

export default function FactorPage({ factor, context, fundamental }: { factor?: FactorRecord; context: ResearchContext; fundamental: FundamentalSnapshot }) {
  const { locale, copy } = useLocale()
  const english = locale === 'en-US'
  const [seriesKey, setSeriesKey] = useState('')
  const selectedSeries = useMemo(() => {
    if (!factor?.series?.length) return undefined
    return factor.series.find((item) => `${item.ticker}:${item.metric}` === seriesKey) ?? factor.series[0]
  }, [factor, seriesKey])

  if (!factor) return <main className="empty"><h1>{english ? 'Factor not found' : '未找到因子'}</h1><p>{english ? 'This factor is not in the current research snapshot.' : '这个因子不在当前研究快照中。'}</p><a href={`${import.meta.env.BASE_URL}factors`}>{english ? 'Back to factor catalog' : '返回因子目录'}</a></main>

  const view = localizeFactorRecord(factor, locale)
  const stats = view.statistics
  const metricOptions = view.series ?? []
  const evidence = view.researchEvidence
  const isFundamental = factor.frequencyIn === 'PIT quarterly reports'
  const sourceNote = isFundamental ? `${english ? 'Fundamental PIT vintage' : '基本面 PIT 版本'} ${fundamental.vintage} · ${fundamental.coverage.date_start} → ${fundamental.coverage.date_end}` : `${context.source} · ${context.snapshotRange}`
  return <main className="page factor-detail-page">
    <a className="back" href={`${import.meta.env.BASE_URL}factors`}>← {english ? 'Factor catalog' : '因子目录'}</a>
    <section className="detail-head"><p className="eyebrow">{view.family}{view.subfamily ? ` / ${view.subfamily}` : ''}</p><h1>{english ? view.displayName : view.displayNameCn ?? view.displayName}</h1><p className="factor-id">{view.id}</p><p className="lede">{view.definition}</p><div className="detail-tags"><span className={`status-pill status-${view.status}`}>{localizedStatus(view.status, locale)}</span><span className="tag">{view.frequencyIn ?? (english ? 'Frequency unavailable' : '频率不可用')} → {view.frequencyOut ?? (english ? 'Frequency unavailable' : '频率不可用')}</span><span className="tag">{english ? 'Public research record' : '公开研究记录'}</span></div></section>
    <section className="panel plain-reading"><p className="eyebrow">{english ? 'START HERE' : '先看这里'}</p><h2>{english ? 'How to read a factor page' : '怎样读懂这张因子页'}</h2><p>{english ? 'A factor is a rule that gives each stock a score from available data. Researchers compare stocks with higher and lower scores to see whether those groups later behaved differently. The score is a research measure; by itself it is not a buy or sell instruction.' : '因子是一条计算规则：用已有数据给每只股票打分。研究者再比较高分组和低分组之后的表现，看两组是否不同。这个分数用于研究，本身不是买卖信号。'} {english ? '“Input → output” shows how often the source data is available and how often the score is formed.' : '“输入频率 → 输出频率”表示源数据多久更新一次，以及因子分数多久形成一次。'}</p></section>
    <section className="panel factor-evidence-card"><p className="eyebrow">{copy.factor.evidenceCard}</p><div className="factor-evidence-grid"><div><span>{view.researchQuestion ? copy.factor.question : copy.factor.interpretation}</span><p>{view.researchQuestion ?? view.intuition ?? view.definition}</p></div><div><span>{copy.factor.status}</span><strong>{localizedStatus(view.status, locale)}</strong><small>{view.researchEvidence?.summary ?? copy.factor.noEvidence}</small></div><div><span>{copy.factor.sample}</span><strong>{sourceNote}</strong><small>{!isFundamental ? `${copy.factor.sourceDate}: ${context.generatedAt.slice(0, 16).replace('T', ' ')} UTC` : `${copy.factor.pitVintage}: ${fundamental.vintage}`}</small></div><div><span>{copy.factor.coverage}</span><strong>{view.coverage?.count?.toLocaleString() ?? '—'}</strong><small>{view.coverage?.missing !== undefined ? `${english ? 'Missing' : '缺失'} ${view.coverage.missing.toLocaleString()}` : (english ? 'Count not published' : '未发布计数')}</small></div></div></section>
    <div className="detail-grid">
      <section className="panel"><p className="eyebrow">PUBLIC DEFINITION</p><h2>{english ? 'How to read it' : '如何理解'}</h2><p className="public-definition">{view.definition}</p><p>{view.intuition ?? (english ? 'Only a descriptive definition is available; no additional economic interpretation is published.' : '当前仅提供描述性定义，尚无额外经济解释。')}</p><dl className="research-dl"><div><dt>{english ? 'Unit' : '单位'}</dt><dd>{view.unit ?? (english ? 'Unavailable' : '不可用')}</dd></div><div><dt>{english ? 'Transform hint' : '变换提示'}</dt><dd>{view.transformHint ?? (english ? 'Unavailable' : '不可用')}</dd></div></dl><p className="panel-note">{english ? 'Exact operators, windows, and per-security signals are not shown on the public page.' : '精确算子、窗口和逐股票信号不在公开页面展示。'}</p></section>
      <section className="panel"><p className="eyebrow">DATA QUALITY</p><h2>{english ? 'Current snapshot' : '当前快照'}</h2><div className="mini-metrics"><MetricCard label={english ? 'Valid values' : '有效值'} value={view.coverage?.count?.toLocaleString() ?? '—'} note={view.coverage?.missing !== undefined ? `${english ? 'Missing' : '缺失'} ${view.coverage.missing.toLocaleString()}` : (english ? 'Full count not provided' : '未提供全量计数')} /><MetricCard label="P01" value={value(stats?.p01)} /><MetricCard label={english ? 'Median' : '中位数'} value={value(stats?.p50)} /><MetricCard label="P99" value={value(stats?.p99)} /></div><p className="panel-note">{sourceNote}</p></section>
    </div>
    <p className="panel-note">{english ? 'P01, P50, and P99 are the 1st, 50th (median), and 99th percentiles of the available cross-section on the displayed date. They describe where this value sits among the sampled stocks; they are not confidence levels. A standardized score is in standard-deviation units, not currency. PIT means point-in-time: the input should have been publicly available by the historical formation date. The historical input timing is shown only when its source record supports it.' : 'P01、P50 和 P99 分别是展示日期有效股票截面的第 1、50（中位数）和第 99 百分位，用来说明数值在样本股票中的相对位置，不是置信水平。标准化分数以标准差为单位，不是金额。PIT（point-in-time，点时）表示输入信息应在历史形成日之前已经公开；只有来源记录支持时，页面才会给出历史输入的具体可用时点。'}</p>
    <section className="panel interpretation-grid"><div><p className="eyebrow">INTERPRETATION</p><h2>{english ? 'Research interpretation' : '研究提示'}</h2><p><strong>{english ? 'Higher: ' : '高值：'}</strong>{view.interpretationHigh ?? (english ? 'Direction is not defined.' : '方向尚未定义。')}</p><p><strong>{english ? 'Lower: ' : '低值：'}</strong>{view.interpretationLow ?? (english ? 'Direction is not defined.' : '方向尚未定义。')}</p></div><div><p className="eyebrow">KNOWN LIMITS</p><h2>{english ? 'Known limits' : '注意事项'}</h2>{view.failureModes?.length ? <ul>{view.failureModes.map((item) => <li key={item}>{item}</li>)}</ul> : <p>{english ? 'No structured failure modes are published.' : '暂无结构化 failure modes。'}</p>}</div></section>
    <section className="panel research-evidence"><p className="eyebrow">RESEARCH EVIDENCE</p><h2>{english ? 'Attribution research' : '归因研究结果'}</h2>{evidence?.summary ? <p>{evidence.summary}</p> : <p>{english ? 'No public IC, grouped-return, or attribution statistics are available; this is not interpreted as validated alpha.' : '当前没有公开的 IC、分层收益或归因统计；这不会被解释为已验证 alpha。'}</p>}{evidence?.metrics?.length ? <div className="evidence-metrics">{evidence.metrics.map((item) => <div key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div> : null}{evidence?.attribution?.length ? <ul>{evidence.attribution.map((item) => <li key={item.label}>{item.label}{english ? `: ${item.value}` : `：${item.value}`}</li>)}</ul> : null}{evidence?.caveats?.length ? <small>{evidence.caveats.join(' · ')}</small> : <small>{english ? 'The public layer keeps sanitized research results only; exact operators and per-security signals are not published.' : '公开层只保留经过脱敏的研究结果；精确算子和逐股票信号不公开。'}</small>}</section>
    <section className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">EXAMPLE SERIES</p><h2>{selectedSeries ? `${selectedSeries.ticker} · ${selectedSeries.metric}` : english ? 'No series available' : '没有可用的序列'}</h2></div>{metricOptions.length ? <label className="series-select"><span>{english ? 'Select series' : '选择序列'}</span><select value={seriesKey || (selectedSeries ? `${selectedSeries.ticker}:${selectedSeries.metric}` : '')} onChange={(event) => setSeriesKey(event.target.value)}>{metricOptions.map((item) => <option key={`${item.ticker}:${item.metric}`} value={`${item.ticker}:${item.metric}`}>{item.ticker} · {item.metric}</option>)}</select></label> : <span className="tag">{english ? 'Series unavailable' : '序列不可用'}</span>}</div>{selectedSeries ? <><p className="chart-caption">{english ? 'This is an example series from the current snapshot and is not representative of the full market.' : '这是当前快照中的示例序列，不代表全市场代表性股票。'}</p><LineChart dates={selectedSeries.dates} series={[{ name: selectedSeries.metric, values: selectedSeries.values, color: '#ef8d5e' }]} /></> : <div className="chart-empty">{english ? 'This factor has no ticker series to display in the current snapshot.' : '该因子当前没有可展示的 ticker 序列。'}</div>}</section>
    <section className="research-boundary"><p><strong>{english ? 'Evidence boundary: ' : '研究边界：'}</strong>{view.status === 'validated' ? (english ? 'This factor has a validation status, but this page still shows snapshot diagnostics only.' : '该因子已有验证状态，但本页面仍只展示快照诊断。') : (english ? 'This page shows a descriptive or experimental snapshot; it does not establish IC, grouped returns, or a trading strategy.' : '当前页面展示的是描述性/实验性快照，不代表 IC、分层收益或交易策略已经验证。')}</p></section>
  </main>
}
